Query Builder
brozeph/reindeer pull request #25
Opened 2017-02-24 02:53 UTC by PN-mruiz

queryBuilder functionality so that there's an option to parse `mongoose-middleware` syntax into a JSON object that ES can understand.

2017-02-28 15:36 UTC, brozeph requested changes
I love where this is going - it looks good so far, but I added a couple thoughts that may allow us to tighten a bit further.

On the whole, I noticed there isn't much usage of the fat arrow function notation (`=>`). Is this something we should consider using throughout the `QueryBuilder` module to keep things more consistent with the `Mapper` module?

2017-02-28 15:36 UTC, brozeph commented on lib/builder.js
> +			} else if (typeof queryOptions.sort === 'object') {
I recommend using the `isPOJO` check on the validators module: <https://github.com/brozeph/reindeer/blob/master/lib/validators.js#L230>

Potentially, things like dates could fall into this and cause breakage (granted, the likelihood of this is low).

2017-02-28 15:36 UTC, brozeph commented on lib/builder.js
> +					} else {
If you put a return in the above `if` statement, you could remove this `else` and have it be the default action on each.

2017-02-28 15:36 UTC, brozeph commented on lib/builder.js
> +		// NOTE: only works with simple cases as at this stage in the software
Probably can kill this comment block here since you've significantly upgraded the sort capability in here...

2017-02-28 15:36 UTC, brozeph commented on lib/builder.js
> +			if (typeof queryOptions.sort === 'string') {
An odd OCD, but I tend to twitch a little when I see `if` blocks followed by `else if` and `else` blocks. 

What if we did something along the lines of the following:

```javascript
// if queryOptions.sort is a string, convert to an array
if (typeof queryOptions.sort === 'string') {
	queryOptions.sort = queryOptions.split(/\,/g).map((field) => field.trim());
}

// handle sort options provided as an Array
if (Array.isArray(queryOptions.sort) && queryOptions.sort.length) {
	sortOptions = queryOptions.sort;
}

// when queryOptions.sort is in object format, convert appropriately
if (validators.isPOJO(queryOptions.sort) {
	// the codez in herr
}
```

2017-02-28 18:13 UTC, PN-mruiz commented
@brozeph changes made

2017-03-01 03:44 UTC, brozeph approved these changes
Super clean - I'll merge, git tag and npm publish tomorrow unless you get to it before me!

2017-03-01 16:23 UTC, merged